"""add_position_symbol_name

Revision ID: 117c4dc320f5
Revises: 002_core_ops
Create Date: 2026-03-25 21:28:01.856895

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "117c4dc320f5"
down_revision: Union[str, None] = "002_core_ops"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("positions", sa.Column("symbol_name", sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("positions", "symbol_name")
    # ### end Alembic commands ###
