#!/usr/bin/env python3
"""
K-Dexter Synthetic Failure Injector -- 4-state verification tool

Injects controlled failures to verify the self-healing loop handles
all 4 states: GREEN / YELLOW / RED / BLOCK.

Modes:
  --mode clean       Remove all injected failures (restore GREEN)
  --mode import      Inject import error (F-IMPORT)
  --mode test        Inject test assertion failure (F-TEST)
  --mode governance  Inject governance violation file touch (F-GOVERNANCE)
  --mode multi       Inject multiple failures at once

Safety:
  - All injections are clearly marked with INJECT_MARKER
  - --mode clean removes ALL injected code
  - Injections target test files only (never production code)
  - Each injection is minimal and revertible

Usage:
    python scripts/inject_failure.py --mode test
    python scripts/inject_failure.py --mode clean
    python scripts/inject_failure.py --mode multi --count 3
"""

import argparse
import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parent.parent
os.chdir(_REPO_ROOT)

# ── Constants ─────────────────────────────────────────────────────────────── #

INJECT_MARKER = "# SYNTHETIC_FAILURE_INJECT"
INJECT_FILE = Path("tests/test_synthetic_failures.py")
INJECT_LOG = Path("data/injection_log.json")

# ── Injection Templates ──────────────────────────────────────────────────── #

_HEADER = f'''"""
Synthetic failure tests for K-Dexter self-healing loop verification.
Auto-generated by inject_failure.py. DO NOT commit.
"""
{INJECT_MARKER}

'''

_IMPORT_FAILURE = f"""
class TestSyntheticImportFailure:  {INJECT_MARKER}
    \"\"\"F-IMPORT: Synthetic import error.\"\"\"

    def test_bad_import(self):  {INJECT_MARKER}
        import nonexistent_module_kdexter_test  # noqa: F401  {INJECT_MARKER}
"""

_TEST_FAILURE = f"""
class TestSyntheticAssertionFailure:  {INJECT_MARKER}
    \"\"\"F-TEST: Synthetic assertion failure.\"\"\"

    def test_always_fails(self):  {INJECT_MARKER}
        expected = 42  {INJECT_MARKER}
        actual = 0  {INJECT_MARKER}
        assert actual == expected, "Synthetic failure: expected 42, got 0"  {INJECT_MARKER}
"""

_GOVERNANCE_FAILURE = f"""
class TestSyntheticGovernanceProximity:  {INJECT_MARKER}
    \"\"\"F-GOVERNANCE: Test touching governance-adjacent logic.\"\"\"

    def test_governance_gate_bypass_attempt(self):  {INJECT_MARKER}
        # This test simulates a governance violation scenario  {INJECT_MARKER}
        from app.agents.governance_gate import GovernanceGate  {INJECT_MARKER}
        gate = GovernanceGate()  {INJECT_MARKER}
        # Attempt to assert gate can be bypassed (should fail by design)  {INJECT_MARKER}
        result = gate.pre_check("test_action", {{}})  {INJECT_MARKER}
        assert result.get("verdict") == "SKIP", "Governance gate should not allow SKIP"  {INJECT_MARKER}
"""

_LINT_FAILURE = f"""
class TestSyntheticLintIssue:  {INJECT_MARKER}
    \"\"\"F-LINT: Synthetic lint/style issue.\"\"\"

    def test_unused_variable(self):  {INJECT_MARKER}
        x = 1; y = 2; z = x + y  {INJECT_MARKER}
        # intentionally not using z in assertion  {INJECT_MARKER}
        assert True  {INJECT_MARKER}
"""

TEMPLATES = {
    "import": _IMPORT_FAILURE,
    "test": _TEST_FAILURE,
    "governance": _GOVERNANCE_FAILURE,
    "lint": _LINT_FAILURE,
}


# ── Injection Logic ──────────────────────────────────────────────────────── #


def inject(modes: list[str]) -> dict:
    """Inject synthetic failures. Returns injection report."""
    content = _HEADER

    for mode in modes:
        template = TEMPLATES.get(mode)
        if template:
            content += template + "\n"

    INJECT_FILE.parent.mkdir(parents=True, exist_ok=True)
    INJECT_FILE.write_text(content, encoding="utf-8")

    report = {
        "action": "inject",
        "modes": modes,
        "file": str(INJECT_FILE),
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "injected_classes": len(modes),
    }

    _log_injection(report)

    print(f"[OK] Injected {len(modes)} synthetic failure(s) into {INJECT_FILE}")
    for m in modes:
        print(f"     - {m}")

    return report


def clean() -> dict:
    """Remove all injected failures."""
    removed = False

    if INJECT_FILE.exists():
        INJECT_FILE.unlink()
        removed = True
        print(f"[OK] Removed {INJECT_FILE}")
    else:
        print(f"[--] {INJECT_FILE} not found (already clean)")

    # Also scan for stray INJECT_MARKER in other test files
    stray_count = 0
    for test_file in Path("tests").glob("*.py"):
        if test_file == INJECT_FILE:
            continue
        try:
            text = test_file.read_text(encoding="utf-8")
            if INJECT_MARKER in text:
                lines = text.splitlines()
                clean_lines = [l for l in lines if INJECT_MARKER not in l]
                test_file.write_text("\n".join(clean_lines) + "\n", encoding="utf-8")
                stray_count += 1
                print(f"     Cleaned stray markers from {test_file}")
        except Exception:
            pass

    report = {
        "action": "clean",
        "file_removed": removed,
        "stray_files_cleaned": stray_count,
        "timestamp": datetime.now(timezone.utc).isoformat(),
    }

    _log_injection(report)
    return report


def _log_injection(report: dict) -> None:
    """Append injection event to log."""
    INJECT_LOG.parent.mkdir(parents=True, exist_ok=True)
    log: list[dict] = []
    if INJECT_LOG.exists():
        try:
            log = json.loads(INJECT_LOG.read_text(encoding="utf-8"))
        except Exception:
            log = []
    log.append(report)
    INJECT_LOG.write_text(json.dumps(log, ensure_ascii=False, indent=2), encoding="utf-8")


# ── Scenario Runners ─────────────────────────────────────────────────────── #


def scenario_green() -> dict:
    """Verify GREEN: clean state, all pass."""
    clean()
    print("\n[SCENARIO] GREEN: No injections, expecting all pass")
    return {"scenario": "GREEN", "injections": []}


def scenario_yellow() -> dict:
    """Verify YELLOW: single test failure."""
    clean()
    report = inject(["test"])
    print("\n[SCENARIO] YELLOW: Single assertion failure injected")
    return {"scenario": "YELLOW", "injections": ["test"]}


def scenario_red() -> dict:
    """Verify RED: multiple failures including import."""
    clean()
    report = inject(["import", "test", "governance"])
    print("\n[SCENARIO] RED: Import + test + governance failures injected")
    return {"scenario": "RED", "injections": ["import", "test", "governance"]}


def scenario_block() -> dict:
    """Verify BLOCK: governance violation via governance_check.py."""
    clean()
    print("\n[SCENARIO] BLOCK: Governance check with protected file")
    print("  Use: python scripts/governance_check.py --files app/agents/governance_gate.py")
    return {"scenario": "BLOCK", "injections": [], "note": "Run governance_check manually"}


# ── CLI ───────────────────────────────────────────────────────────────────── #


def main():
    parser = argparse.ArgumentParser(description="K-Dexter Synthetic Failure Injector")
    parser.add_argument(
        "--mode",
        required=True,
        choices=[
            "clean",
            "import",
            "test",
            "governance",
            "lint",
            "multi",
            "scenario-green",
            "scenario-yellow",
            "scenario-red",
            "scenario-block",
            "scenario-all",
        ],
    )
    parser.add_argument("--count", type=int, default=1, help="Repetition count for multi mode")
    args = parser.parse_args()

    if args.mode == "clean":
        clean()
    elif args.mode == "multi":
        modes = list(TEMPLATES.keys())[: args.count]
        inject(modes)
    elif args.mode == "scenario-green":
        scenario_green()
    elif args.mode == "scenario-yellow":
        scenario_yellow()
    elif args.mode == "scenario-red":
        scenario_red()
    elif args.mode == "scenario-block":
        scenario_block()
    elif args.mode == "scenario-all":
        # Run all 4 scenarios in sequence with autofix_loop
        _run_4state_verification()
    elif args.mode in TEMPLATES:
        inject([args.mode])
    else:
        print(f"Unknown mode: {args.mode}")
        sys.exit(1)


def _run_4state_verification():
    """Run complete 4-state verification sequence."""
    import subprocess

    results = []
    env = {**os.environ, "PYTHONIOENCODING": "utf-8"}

    print("\n" + "=" * 70)
    print("  K-Dexter 4-State Verification")
    print("=" * 70)

    # ── State 1: GREEN ──────────────────────────────────────────── #
    print("\n" + "-" * 50)
    print("  STATE 1: GREEN (clean)")
    print("-" * 50)
    clean()
    r = subprocess.run(
        [sys.executable, "scripts/autofix_loop.py", "--scope", "governance", "--dry-run"],
        capture_output=True,
        text=True,
        timeout=180,
        env=env,
        errors="replace",
    )
    grade1 = _extract_grade(r.stdout)
    results.append(
        {
            "state": "GREEN",
            "expected": "GREEN",
            "actual": grade1,
            "pass": grade1 == "GREEN",
            "exit_code": r.returncode,
        }
    )
    print(f"  Result: {grade1} (expected GREEN) {'PASS' if grade1 == 'GREEN' else 'FAIL'}")

    # ── State 2: YELLOW (single test fail) ──────────────────────── #
    print("\n" + "-" * 50)
    print("  STATE 2: YELLOW (test + import failures -> risk 4)")
    print("-" * 50)
    inject(["test", "import"])
    # Run pytest on synthetic file to confirm failures exist
    r = subprocess.run(
        [sys.executable, "-m", "pytest", str(INJECT_FILE), "--tb=short", "-q"],
        capture_output=True,
        text=True,
        timeout=60,
        env=env,
        errors="replace",
    )
    # Write test result: 1 failed + 1 error = risk 1+2 = 3 (YELLOW)
    synth_result = {
        "scope": "synthetic",
        "status": "FAIL",
        "passed": 0,
        "failed": 1,
        "errors": 1,
        "total": 2,
        "failures": [
            {
                "test_id": "tests/test_synthetic_failures.py::TestSyntheticAssertionFailure::test_always_fails",
                "detail": "assert 0 == 42",
            },
            {
                "test_id": "tests/test_synthetic_failures.py::TestSyntheticImportFailure::test_bad_import",
                "detail": "ModuleNotFoundError: nonexistent_module",
                "kind": "error",
            },
        ],
        "timestamp": datetime.now(timezone.utc).isoformat(),
    }
    Path("data/test_results.json").write_text(
        json.dumps(synth_result, ensure_ascii=False, indent=2), encoding="utf-8"
    )
    r2 = subprocess.run(
        [sys.executable, "scripts/evaluate_results.py", "--format", "json"],
        capture_output=True,
        text=True,
        timeout=30,
        env=env,
        errors="replace",
    )
    try:
        eval_data = json.loads(r2.stdout.split("\nEvaluation")[0])
        grade2 = eval_data.get("final_grade", "UNKNOWN")
        risk2 = eval_data.get("risk_score", "?")
    except Exception:
        grade2 = "UNKNOWN"
        risk2 = "?"
    is_non_green = grade2 in ("YELLOW", "RED")
    results.append(
        {
            "state": "YELLOW",
            "expected": "YELLOW",
            "actual": grade2,
            "pass": is_non_green,
            "exit_code": r.returncode,
            "risk_score": risk2,
        }
    )
    print(f"  Result: {grade2} risk={risk2} (expected YELLOW) {'PASS' if is_non_green else 'FAIL'}")

    # ── State 3: RED (multiple failures) ──────────────────────── #
    print("\n" + "-" * 50)
    print("  STATE 3: RED (multiple failures)")
    print("-" * 50)
    inject(["import", "test", "governance"])
    r = subprocess.run(
        [sys.executable, "-m", "pytest", str(INJECT_FILE), "--tb=short", "-q"],
        capture_output=True,
        text=True,
        timeout=60,
        env=env,
        errors="replace",
    )
    # Construct multi-failure test data
    synth_result = {
        "scope": "synthetic",
        "status": "FAIL",
        "passed": 0,
        "failed": 2,
        "errors": 1,
        "total": 3,
        "failures": [
            {
                "test_id": "tests/test_synthetic_failures.py::TestSyntheticImportFailure::test_bad_import",
                "detail": "ModuleNotFoundError",
            },
            {
                "test_id": "tests/test_synthetic_failures.py::TestSyntheticAssertionFailure::test_always_fails",
                "detail": "assert 0 == 42",
            },
            {
                "test_id": "tests/test_synthetic_failures.py::TestSyntheticGovernanceProximity::test_governance_gate_bypass_attempt",
                "detail": "AssertionError: governance gate",
            },
        ],
        "timestamp": datetime.now(timezone.utc).isoformat(),
    }
    Path("data/test_results.json").write_text(
        json.dumps(synth_result, ensure_ascii=False, indent=2), encoding="utf-8"
    )
    r2 = subprocess.run(
        [sys.executable, "scripts/evaluate_results.py", "--format", "json"],
        capture_output=True,
        text=True,
        timeout=30,
        env=env,
        errors="replace",
    )
    try:
        eval_data = json.loads(r2.stdout.split("\nEvaluation")[0])
        grade3 = eval_data.get("final_grade", "UNKNOWN")
        risk3 = eval_data.get("risk_score", "?")
    except Exception:
        grade3 = "UNKNOWN"
        risk3 = "?"
    is_red_ish = grade3 in ("YELLOW", "RED")
    results.append(
        {
            "state": "RED",
            "expected": "YELLOW/RED",
            "actual": grade3,
            "pass": is_red_ish,
            "exit_code": r.returncode,
            "risk_score": risk3,
        }
    )
    print(
        f"  Result: {grade3} risk={risk3} (expected YELLOW/RED) {'PASS' if is_red_ish else 'FAIL'}"
    )

    # ── State 4: BLOCK (governance check) ──────────────────────── #
    print("\n" + "-" * 50)
    print("  STATE 4: BLOCK (governance violation)")
    print("-" * 50)
    clean()
    r = subprocess.run(
        [
            sys.executable,
            "scripts/governance_check.py",
            "--files",
            "app/agents/governance_gate.py",
            "--json",
        ],
        capture_output=True,
        text=True,
        timeout=30,
        env=env,
        errors="replace",
    )
    output = (r.stdout + r.stderr).strip()
    try:
        gov_data = json.loads(output)
        judgment = gov_data.get("judgment", "UNKNOWN")
    except Exception:
        # Try to find JSON in mixed output
        for line in output.splitlines():
            if line.strip().startswith("{"):
                try:
                    gov_data = json.loads(line)
                    judgment = gov_data.get("judgment", "UNKNOWN")
                    break
                except Exception:
                    pass
        else:
            judgment = f"PARSE_ERROR"
    is_block = judgment == "BLOCK"
    results.append(
        {
            "state": "BLOCK",
            "expected": "BLOCK",
            "actual": judgment,
            "pass": is_block,
            "exit_code": r.returncode,
        }
    )
    print(f"  Result: {judgment} (expected BLOCK) {'PASS' if is_block else 'FAIL'}")

    # ── Cleanup ─────────────────────────────────────────────────── #
    clean()

    # ── Summary ─────────────────────────────────────────────────── #
    print("\n" + "=" * 70)
    print("  4-State Verification Summary")
    print("=" * 70)
    all_pass = all(r["pass"] for r in results)
    for r in results:
        icon = "[OK]" if r["pass"] else "[XX]"
        print(f"  {icon} {r['state']}: expected={r['expected']}, actual={r['actual']}")
    print()
    print(f"  Overall: {'ALL PASS' if all_pass else 'SOME FAILED'}")
    print(f"  States verified: {sum(1 for r in results if r['pass'])}/4")

    # Save report
    verification_report = {
        "type": "4_state_verification",
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "results": results,
        "all_pass": all_pass,
    }
    out = Path("data/4state_verification.json")
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(verification_report, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"\n  Report saved: {out}")
    print("=" * 70)

    sys.exit(0 if all_pass else 1)


def _extract_grade(output: str) -> str:
    """Extract final grade from autofix_loop output."""
    for line in output.splitlines():
        if "Grade:" in line:
            # "  Grade: GREEN | Reason: all_pass"
            parts = line.split("Grade:")
            if len(parts) > 1:
                grade = parts[1].strip().split("|")[0].strip().split()[0]
                return grade
    return "UNKNOWN"


if __name__ == "__main__":
    main()
