"""
Self-Improvement Loop — K-Dexter AOS v4

Periodically analyses recent trading performance, identifies underperforming
parameters, and proposes incremental updates.

Triggered by (failure_taxonomy.md Section 2):
  - STRATEGY HIGH (FIRST/REPEAT)
  - STRATEGY MEDIUM (FIRST/REPEAT)
  - GOVERNANCE MEDIUM (FIRST/REPEAT)

Phases:
  1. ANALYZE   — sample recent performance data, identify weak parameters
  2. PROPOSE   — generate parameter update proposals
  3. BACKTEST  — validate proposals against historical data
  4. APPLY     — apply validated changes to Rule Ledger (with provenance)
  5. VERIFY    — confirm improvement via completion check

Mandatory items applied (all 18 — no exemptions for Self-Improvement):
  M-03 risk check, M-04 security check, M-07 evidence (always),
  M-10 provenance (always), M-16 completion check

Loop ceiling (thresholds.py): per_incident=3, per_day=5, per_week=15
"""
from __future__ import annotations

import asyncio
import uuid
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Optional, Callable, Awaitable

from kdexter.audit.evidence_store import EvidenceBundle, EvidenceStore
from kdexter.ledger.rule_ledger import (
    Rule, RuleLedger, RuleProvenance, ProvenanceRequiredError,
)
from kdexter.loops.concurrency import (
    LoopCounter, LoopCeilingExceededError,
    LoopPriority, LoopPriorityQueue, RuleLedgerLock,
)
from kdexter.state_machine.security_state import SecurityStateContext, SecurityStateEnum


# ─────────────────────────────────────────────────────────────────────────── #
# Phase enum
# ─────────────────────────────────────────────────────────────────────────── #

class SIPhase(Enum):
    IDLE = "IDLE"
    ANALYZE = "ANALYZE"
    PROPOSE = "PROPOSE"
    BACKTEST = "BACKTEST"
    APPLY = "APPLY"
    VERIFY = "VERIFY"
    FAILED = "FAILED"


# ─────────────────────────────────────────────────────────────────────────── #
# Data models
# ─────────────────────────────────────────────────────────────────────────── #

@dataclass
class PerformanceSample:
    """A snapshot of recent trading performance metrics."""
    sample_id: str = field(default_factory=lambda: f"PS-{uuid.uuid4().hex[:8].upper()}")
    sampled_at: datetime = field(default_factory=datetime.utcnow)
    win_rate: float = 0.0           # 0.0 ~ 1.0
    avg_return: float = 0.0         # per-trade average return
    max_drawdown: float = 0.0       # maximum drawdown observed
    sharpe_ratio: float = 0.0
    total_trades: int = 0
    failure_ids: list[str] = field(default_factory=list)  # triggering failures


@dataclass
class ImprovementProposal:
    """A proposed parameter change generated by analysis."""
    proposal_id: str = field(default_factory=lambda: f"IP-{uuid.uuid4().hex[:8].upper()}")
    parameter_name: str = ""        # which parameter to change
    current_value: str = ""         # current value (serialized)
    proposed_value: str = ""        # proposed new value
    rationale: str = ""             # why this change
    backtest_score: Optional[float] = None   # backtest result (None = not yet tested)
    accepted: bool = False
    created_at: datetime = field(default_factory=datetime.utcnow)


@dataclass
class SIResult:
    """Result of one Self-Improvement cycle."""
    cycle_id: str
    incident_id: str
    phase_reached: SIPhase
    proposals_generated: int = 0
    proposals_accepted: int = 0
    rules_created: int = 0
    error: Optional[str] = None
    started_at: datetime = field(default_factory=datetime.utcnow)
    completed_at: Optional[datetime] = None

    def finish(self, phase: SIPhase, error: Optional[str] = None) -> None:
        self.phase_reached = phase
        self.error = error
        self.completed_at = datetime.utcnow()


# ─────────────────────────────────────────────────────────────────────────── #
# Hooks (dependency injection)
# ─────────────────────────────────────────────────────────────────────────── #

@dataclass
class SIHooks:
    """
    Injectable callbacks for Self-Improvement Loop.
    Default: stubs that produce minimal proposals.
    """
    # Analyze: returns PerformanceSample from recent data
    analyze: Callable[[], Awaitable[PerformanceSample]] = None

    # Propose: given sample, returns list of proposals
    propose: Callable[[PerformanceSample], Awaitable[list[ImprovementProposal]]] = None

    # Backtest: given proposal, returns score 0.0~1.0 (higher = better)
    backtest: Callable[[ImprovementProposal], Awaitable[float]] = None

    # Risk check (M-03)
    check_risk: Callable[[], Awaitable[bool]] = None

    # Security check (M-04)
    check_security: Callable[[], Awaitable[bool]] = None

    def __post_init__(self) -> None:
        if self.analyze is None:
            async def _default_analyze() -> PerformanceSample:
                return PerformanceSample(win_rate=0.5, avg_return=0.001, total_trades=100)
            self.analyze = _default_analyze

        if self.propose is None:
            async def _default_propose(sample: PerformanceSample) -> list[ImprovementProposal]:
                return []
            self.propose = _default_propose

        if self.backtest is None:
            async def _default_backtest(proposal: ImprovementProposal) -> float:
                return 0.8  # default pass
            self.backtest = _default_backtest

        if self.check_risk is None:
            async def _default_risk() -> bool:
                return True
            self.check_risk = _default_risk

        if self.check_security is None:
            async def _default_security() -> bool:
                return True
            self.check_security = _default_security


# ─────────────────────────────────────────────────────────────────────────── #
# Self-Improvement Loop
# ─────────────────────────────────────────────────────────────────────────── #

# Minimum backtest score to accept a proposal
BACKTEST_ACCEPTANCE_THRESHOLD: float = 0.6


class SelfImprovementLoop:
    """
    Performance-driven parameter self-improvement loop.

    Single instance — queued if Recovery or another SI is active.
    Changes go through Rule Ledger with full provenance (M-10).

    Usage:
        loop = SelfImprovementLoop(
            rule_ledger=ledger, rule_lock=lock,
            evidence_store=store, security=sec,
            loop_counter=counter, loop_queue=queue,
        )
        loop.accept_trigger("F-S-001", "STRATEGY", "HIGH")
        result = await loop.run()
    """

    def __init__(
        self,
        rule_ledger: RuleLedger,
        rule_lock: RuleLedgerLock,
        evidence_store: EvidenceStore,
        security: SecurityStateContext,
        loop_counter: LoopCounter,
        loop_queue: LoopPriorityQueue,
        hooks: Optional[SIHooks] = None,
    ) -> None:
        self._ledger = rule_ledger
        self._lock = rule_lock
        self._evidence = evidence_store
        self._security = security
        self._counter = loop_counter
        self._queue = loop_queue
        self._hooks = hooks or SIHooks()

        self._phase = SIPhase.IDLE
        self._active = False
        self._trigger_failures: list[str] = []
        self._incident_id: str = ""

    # ── Properties ───────────────────────────────────────────────────────── #

    @property
    def is_active(self) -> bool:
        return self._active

    @property
    def current_phase(self) -> SIPhase:
        return self._phase

    # ── Public API ───────────────────────────────────────────────────────── #

    def accept_trigger(
        self,
        failure_id: str,
        domain: str,
        severity: str,
        incident_id: Optional[str] = None,
    ) -> None:
        """Accept a failure trigger for self-improvement."""
        self._trigger_failures.append(failure_id)
        self._incident_id = incident_id or f"SI-{uuid.uuid4().hex[:8].upper()}"

    async def run(self) -> SIResult:
        """
        Execute one self-improvement cycle.
        Phases: ANALYZE → PROPOSE → BACKTEST → APPLY → VERIFY
        """
        cycle_id = f"SI-{uuid.uuid4().hex[:8].upper()}"
        result = SIResult(
            cycle_id=cycle_id,
            incident_id=self._incident_id,
            phase_reached=SIPhase.IDLE,
        )

        # Ceiling check
        try:
            self._counter.check_and_record("SELF_IMPROVEMENT", self._incident_id)
        except LoopCeilingExceededError as exc:
            result.finish(SIPhase.FAILED, str(exc))
            return result

        self._active = True
        self._queue.mark_active(LoopPriority.SELF_IMPROVEMENT)

        try:
            # Phase 1: ANALYZE
            sample = await self._phase_analyze(result)

            # Phase 2: PROPOSE
            proposals = await self._phase_propose(sample, result)
            result.proposals_generated = len(proposals)

            if not proposals:
                self._emit("NO_PROPOSALS", {"cycle_id": cycle_id})
                result.finish(SIPhase.PROPOSE)
                return result

            # Phase 3: BACKTEST
            accepted = await self._phase_backtest(proposals, result)
            result.proposals_accepted = len(accepted)

            if not accepted:
                self._emit("NO_ACCEPTED_PROPOSALS", {"cycle_id": cycle_id})
                result.finish(SIPhase.BACKTEST)
                return result

            # Phase 4: APPLY
            rules_created = await self._phase_apply(accepted, result)
            result.rules_created = rules_created

            # Phase 5: VERIFY
            await self._phase_verify(result)

            result.finish(SIPhase.VERIFY)

        except SIFailureError as exc:
            self._phase = SIPhase.FAILED
            self._emit("SI_FAILED", {"reason": str(exc), "cycle_id": cycle_id})
            result.finish(SIPhase.FAILED, str(exc))

        except Exception as exc:
            self._phase = SIPhase.FAILED
            result.finish(SIPhase.FAILED, str(exc))

        finally:
            self._active = False
            self._queue.mark_inactive(LoopPriority.SELF_IMPROVEMENT)
            self._trigger_failures.clear()

        return result

    # ── Phase implementations ────────────────────────────────────────────── #

    async def _phase_analyze(self, result: SIResult) -> PerformanceSample:
        """Phase 1: Sample recent performance data."""
        self._phase = SIPhase.ANALYZE

        sample = await self._hooks.analyze()
        sample.failure_ids = list(self._trigger_failures)

        self._emit("ANALYZE_COMPLETE", {
            "sample_id": sample.sample_id,
            "win_rate": sample.win_rate,
            "avg_return": sample.avg_return,
            "total_trades": sample.total_trades,
        })
        return sample

    async def _phase_propose(
        self,
        sample: PerformanceSample,
        result: SIResult,
    ) -> list[ImprovementProposal]:
        """Phase 2: Generate improvement proposals."""
        self._phase = SIPhase.PROPOSE

        # M-03: risk check before proposing changes
        if not await self._hooks.check_risk():
            raise SIFailureError("M-03 risk check failed in PROPOSE phase")

        proposals = await self._hooks.propose(sample)

        self._emit("PROPOSE_COMPLETE", {
            "proposal_count": len(proposals),
            "proposals": [p.proposal_id for p in proposals],
        })
        return proposals

    async def _phase_backtest(
        self,
        proposals: list[ImprovementProposal],
        result: SIResult,
    ) -> list[ImprovementProposal]:
        """Phase 3: Backtest each proposal, accept those above threshold."""
        self._phase = SIPhase.BACKTEST

        accepted = []
        for proposal in proposals:
            score = await self._hooks.backtest(proposal)
            proposal.backtest_score = score

            if score >= BACKTEST_ACCEPTANCE_THRESHOLD:
                proposal.accepted = True
                accepted.append(proposal)

            self._emit("BACKTEST_RESULT", {
                "proposal_id": proposal.proposal_id,
                "score": score,
                "accepted": proposal.accepted,
            })

        return accepted

    async def _phase_apply(
        self,
        accepted: list[ImprovementProposal],
        result: SIResult,
    ) -> int:
        """Phase 4: Apply accepted proposals to Rule Ledger."""
        self._phase = SIPhase.APPLY

        # M-04: security check before applying
        if not await self._hooks.check_security():
            raise SIFailureError("M-04 security check failed in APPLY phase")

        rules_created = 0
        for proposal in accepted:
            # M-10: provenance required for every rule change
            provenance = RuleProvenance(
                source_incident=self._incident_id,
                author_layer="L9",  # Self-Improvement Engine = L9
                rationale=f"SI proposal {proposal.proposal_id}: {proposal.rationale}",
            )

            rule = Rule(
                name=f"si_{proposal.parameter_name}",
                condition=f"{proposal.parameter_name} = {proposal.proposed_value}",
                action="APPLY_PARAMETER",
                provenance=provenance,
            )

            await self._ledger.create(rule, LoopPriority.SELF_IMPROVEMENT)
            rules_created += 1

            self._emit("RULE_CREATED", {
                "proposal_id": proposal.proposal_id,
                "rule_id": rule.rule_id,
                "parameter": proposal.parameter_name,
            })

        return rules_created

    async def _phase_verify(self, result: SIResult) -> None:
        """Phase 5: Verify improvement was applied correctly."""
        self._phase = SIPhase.VERIFY

        # M-16: completion check (simplified — verify rules are in ledger)
        rule_count = len(self._ledger.list_all(enabled_only=True))

        self._emit("VERIFY_COMPLETE", {
            "cycle_id": result.cycle_id,
            "rules_created": result.rules_created,
            "total_active_rules": rule_count,
        })

    # ── Helpers ──────────────────────────────────────────────────────────── #

    def _emit(self, action: str, artifacts: dict) -> None:
        """M-07: emit EvidenceBundle for every phase."""
        bundle = EvidenceBundle(
            trigger=f"SelfImprovementLoop.{action}",
            actor="SelfImprovementLoop",
            action=action,
            artifacts=[artifacts],
        )
        self._evidence.store(bundle)


# ─────────────────────────────────────────────────────────────────────────── #
# Exceptions
# ─────────────────────────────────────────────────────────────────────────── #

class SIFailureError(Exception):
    """Self-Improvement Loop phase failure."""
    pass
